name: generate-snake-game-from-github-contribution-grid

on: [push]

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest
    name: Generate Snake Game Animation
    steps:
    - uses: actions/checkout@v2
    - name: Generate Snake Game from Contributions
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
